blockchain:
  bonding_denom: "basetcro"
  account_address_prefix: "tcro"
  account_pubkey_prefix: "tcropub"
  validator_address_prefix: "tcrocncl"
  validator_pub_key_prefix: "tcrocncl"
  con_node_address_prefix: "tcrocnclcons"
  con_node_pubkey_prefix: "tcrocnclconspub"

index_service:
  enable: true
  mode: "TENDERMINT_DIRECT"
  window_size: 50
  projection:
    enables: [
        "AccountMessage",
        "AccountTransaction",
        "Block",
        "BlockEvent",
        "ChainStats",
        "Proposal",
        "Transaction",
        "Validator",
        "ValidatorStats",
        "NFT",
      #      "CryptoComNFT",
        "IBCChannel",
      #      "IBCChannelTxMsgTrace",
        "IBCChannelMessage",
        "BridgePendingActivity",
        "Example",
    ]
    extra_configs:
      BridgePendingActivity:
        this_chain_id: "testnet-croeseid-4"
        this_chain_name: "Crypto.org-Chain"
        counterparty_chain_name: "Cronos"
        channel_id: "channel-131"
        starting_height: 899374
  cronjob:
    enables: [ ]
  cosmos_version_enabled_height:
    v0_42_7: 0
  github_api:
    username: "public"
    token: "token"
    migration_repo_ref: ""

http_service:
  enable: true
  listening_address: "0.0.0.0:8080"
  route_prefix: "/"
  cors_allowed_origins: [ ]
  cors_allowed_methods: [ "HEAD", "GET" ]
  cors_allowed_headers: [ "Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time" ]

tendermint_app:
  http_rpc_url: "https://testnet-croeseid-4.crypto.org:26657"
  insecure: false
  # When strict_genesis_parsing enabled, genssi parsing will reject any non-Cosmos SDK built-in module
  # inside genesis file.
  strict_genesis_parsing: false

cosmos_app:
  http_rpc_url: "https://testnet-croeseid-4.crypto.org:1317"
  insecure: false

debug:
  pprof_enable: false
  pprof_listening_address: "0.0.0.0:3000"

postgres:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  name: "postgres"
  schema: "public"
  ssl: true
  pool_max_conns: 100
  pool_min_conns: 0
  pool_max_conn_life_time: "1h"
  pool_max_conn_idle_time: "30m"
  pool_health_check_interval: "1m"

logger:
  level: "debug"
  color: false

prometheus:
  enable: false
  exportpath: "/metrics"
  port: "9090"

server_github_api:
  migration_repo_ref: ""